// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-tnZA5n4E5rhmgMejlRa1QkacyXY6fL8',
    appId: '1:116869171794:web:234a329253562e81dded8b',
    messagingSenderId: '116869171794',
    projectId: 'skribble-39177',
    authDomain: 'skribble-39177.firebaseapp.com',
    databaseURL: 'https://skribble-39177-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skribble-39177.firebasestorage.app',
    measurementId: 'G-2P90TQR81J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTYpEQLITkv1i34bKs-77aI35-fTVPgJA',
    appId: '1:116869171794:android:1484a5606874ecf2dded8b',
    messagingSenderId: '116869171794',
    projectId: 'skribble-39177',
    databaseURL: 'https://skribble-39177-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skribble-39177.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-n_g6kQOeFMX3iJZI3RAeBy-5FdmfGtM',
    appId: '1:116869171794:ios:79bd4523bee0c9e0dded8b',
    messagingSenderId: '116869171794',
    projectId: 'skribble-39177',
    databaseURL: 'https://skribble-39177-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skribble-39177.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}