name: app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # firebase_core: ^2.32.0
  # cloud_firestore: ^4.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  random_string: ^2.3.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  provider: ^6.1.4
  firebase_ui_auth: ^1.16.1
  splash_master: ^0.0.2
  lottie: ^3.3.1
  logging: ^1.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700

  assets:
    - assets/images/splash_lottie.json
